### ISSUE TITLE
ClosureCompiler no longer works - jit and load-config

### ISSUE THREAD

**Issue by cristian-sima** [thanpolas/grunt-closure-tools#70]
Hi. I have used it for months and today it is not working. It stops with this message

![image](https://cloud.githubusercontent.com/assets/12199042/15248891/4efae744-1925-11e6-902b-f55df99c46dc.png)

- windows 10

![image](https://cloud.githubusercontent.com/assets/12199042/15248914/62dbf5f0-1925-11e6-82ae-3cdfa5a2e0f6.png)

**Comment by thanpolas** [comment]
hmmm there is no error message that would help here, it just aborts :/

**Comment by cristian-sima** [comment]
@thanpolas  Why?

**Comment by thanpolas** [comment]
try to run the command with the debug option like so:

`grunt build --debug --verbose`

**Comment by cristian-sima** [comment]
What is `build` ?

**Comment by thanpolas** [comment]
whatever your task is, i don't know how you call it, i can't see from the screenshot

**Comment by cristian-sima** [comment]
same


![image](https://cloud.githubusercontent.com/assets/12199042/15251336/8fedc4f4-1931-11e6-805a-4eb5dd82f13d.png)

**Comment by cristian-sima** [comment]
Gruntfile.js

```
/* minifyOnSave:false */
/*global module:false, require */
module.exports = function (grunt) {

  // load just the ones which we need
  require('jit-grunt')(grunt);

  // measures the time each task takes
  require('time-grunt')(grunt);

  // load grunt config
  require('load-grunt-config')(grunt, {
    jitGrunt: true
  });
};
```

**Comment by thanpolas** [comment]
I'm sorry, I still can't tell what's wrong, there's no error or stack trace to indicate something...

What changed since the last time it was working? Is it working on your colleagues?

**Comment by cristian-sima** [comment]
A lot of Windows 10 updates

**Comment by cristian-sima** [comment]
It is just me working on this. Yesterday it was working fine

**Comment by cristian-sima** [comment]
Hi.

I figured out the situation the problem occurs:

- using `jit-grunt`
- using `load-grunt-config`, but only when `jitGrunt` is set to `true`:
```
  require('load-grunt-config')(grunt, {
     jitGrunt: true
  });
```
It appears that `closureCompiler` is the only task that has this problem.

Can someone make something for this?

**Comment by cristian-sima** [comment]
I got the solution!

You have to tell `jit` that `closureCompiler ` belongs to this package, using [static mapping](https://github.com/shootaroo/jit-grunt#static-mappings)

```
  // load just the ones which we need
  require('jit-grunt')(grunt, {
    closureCompiler: "grunt-closure-tools"
  });
```
