### ISSUE TITLE
Add support for Node 8 (update grunt version).

### ISSUE THREAD

**Issue by pulekies** [thanpolas/grunt-closure-tools#73]
Currently grunt-closure-tools relies on graceful-fs@1.2.3

Unfortunately that is not compatible with Node 8 and will cause the following error:

`npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.`

Seems like the fix is as easy as just updating package.json to point at a more recent version of grunt (which relies on graceful-fs).

**Comment by thanpolas** [comment]
@pulekies thank you for this, if you could submit a PR it'd be fast as I'm tied up right now.

**Comment by pulekies** [comment]
Thanks! I submitted pull request   #74.

There were build failures, but as far as I can see they are related to running on an out of date environment.

**Comment by thanpolas** [comment]
Version 1.0.0 is now on NPM

**Comment by pulekies** [comment]
Thanks! I appreciate you taking the time to update the test environment.
